import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import localFont from "next/font/local";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const argentCF = localFont({
  src: "../public/fonts/argent-cf-regular.woff2",
  variable: "--font-argent",
  display: "swap",
});

export const metadata = {
  title: "E-invoicing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${argentCF.variable} antialiased`}>
        <div>
          <Header />
        </div>
        <div>{children}</div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
